const CATEGORIES = {
  INTERNATIONAL: "International",
  WORLD: "World Day",
  HEALTH: "Health",
  ENVIRONMENT: "Environment",
  INDIA: "India National",
  FESTIVAL: "Festival",
  RELIGIOUS: "Religious",
  CULTURAL: "Cultural",
  SCIENCE: "Science & Tech",
  HUMAN_RIGHTS: "Human Rights",
  EDUCATION: "Education",
};

let importantDays = [
  // ── JANUARY ──
  { date: "01-01", name: "New Year's Day", description: "The first day of the Gregorian calendar year, celebrated worldwide.", category: CATEGORIES.CULTURAL, emoji: "🎆" },
  { date: "01-01", name: "Global Family Day", description: "A day of peace and sharing, celebrating families worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "👪" },
  { date: "01-04", name: "World Braille Day", description: "Honors Louis Braille, inventor of the Braille system for visually impaired people.", category: CATEGORIES.INTERNATIONAL, emoji: "👁️" },
  { date: "01-06", name: "World Day of War Orphans", description: "Raises awareness about difficulties faced by orphans of war worldwide.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🕊️" },
  { date: "01-09", name: "NRI Day (Pravasi Bharatiya Divas)", description: "Celebrates contributions of overseas Indian community to India.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "01-10", name: "World Hindi Day", description: "Commemorates the anniversary of the first World Hindi Conference in 1975.", category: CATEGORIES.INDIA, emoji: "🗣️" },
  { date: "01-11", name: "National Human Trafficking Awareness Day", description: "Raises awareness of the illegal practice of human trafficking.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🛑" },
  { date: "01-12", name: "National Youth Day (India)", description: "Celebrates Swami Vivekananda's birthday. Theme: youth empowerment.", category: CATEGORIES.INDIA, emoji: "⚡" },
  { date: "01-13", name: "Lohri", description: "Punjabi winter harvest festival celebrated with bonfires, dancing and sweets.", category: CATEGORIES.FESTIVAL, emoji: "🔥" },
  { date: "01-14", name: "Makar Sankranti", description: "Hindu harvest festival marking the sun's transit into Capricorn.", category: CATEGORIES.FESTIVAL, emoji: "☀️" },
  { date: "01-14", name: "Pongal", description: "Tamil harvest festival; four-day celebration with sugarcane and kolam art.", category: CATEGORIES.FESTIVAL, emoji: "🌾" },
  { date: "01-15", name: "Indian Army Day", description: "Celebrates the Indian Army and its contributions to the nation.", category: CATEGORIES.INDIA, emoji: "🎖️" },
  { date: "01-23", name: "Parakram Diwas", description: "Birth anniversary of Netaji Subhas Chandra Bose.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "01-24", name: "National Girl Child Day (India)", description: "Promotes rights and welfare of girl children in India.", category: CATEGORIES.INDIA, emoji: "👧" },
  { date: "01-24", name: "International Day of Education", description: "Role of education for peace and development.", category: CATEGORIES.EDUCATION, emoji: "📚" },
  { date: "01-25", name: "National Voters' Day (India)", description: "Encourages new voters to participate in the democratic process.", category: CATEGORIES.INDIA, emoji: "🗳️" },
  { date: "01-25", name: "National Tourism Day (India)", description: "Raises awareness about the importance of tourism for the economy.", category: CATEGORIES.INDIA, emoji: "✈️" },
  { date: "01-26", name: "Republic Day of India", description: "India's constitution came into effect on this day in 1950.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "01-26", name: "International Customs Day", description: "Recognizes the role of customs officials in maintaining border security.", category: CATEGORIES.INTERNATIONAL, emoji: "🛂" },
  { date: "01-27", name: "International Holocaust Remembrance Day", description: "UN day to honor victims of the Holocaust during WWII.", category: CATEGORIES.INTERNATIONAL, emoji: "🕯️" },
  { date: "01-28", name: "Data Privacy Day", description: "Raises awareness about online privacy and data protection.", category: CATEGORIES.SCIENCE, emoji: "🔐" },
  { date: "01-28", name: "Lala Lajpat Rai Birth Anniversary", description: "Tribute to the prominent Indian freedom fighter.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "01-30", name: "Martyrs' Day (India)", description: "Commemorates the assassination of Mahatma Gandhi in 1948.", category: CATEGORIES.INDIA, emoji: "🙏" },
  { date: "01-30", name: "World Leprosy Eradication Day", description: "Promotes understanding of leprosy and support for those affected.", category: CATEGORIES.HEALTH, emoji: "🏥" },

  // ── FEBRUARY ──
  { date: "02-01", name: "Indian Coast Guard Day", description: "Celebrates the anniversary of the Coast Guard's foundation.", category: CATEGORIES.INDIA, emoji: "⚓" },
  { date: "02-02", name: "World Wetlands Day", description: "Marks the adoption of the Ramsar Convention on Wetlands in 1971.", category: CATEGORIES.ENVIRONMENT, emoji: "🌿" },
  { date: "02-04", name: "World Cancer Day", description: "International awareness and education day about cancer prevention.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "02-06", name: "International Day of Zero Tolerance for Female Genital Mutilation", description: "Promotes the eradication of FGM globally.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🛑" },
  { date: "02-08", name: "Safer Internet Day", description: "Promotes safer and more responsible use of online technology.", category: CATEGORIES.SCIENCE, emoji: "🌐" },
  { date: "02-10", name: "National Deworming Day (India)", description: "Initiative to deworm children across India.", category: CATEGORIES.INDIA, emoji: "💊" },
  { date: "02-10", name: "World Pulses Day", description: "Celebrates the nutritional and environmental benefits of pulses.", category: CATEGORIES.WORLD, emoji: "🌾" },
  { date: "02-11", name: "International Day of Women and Girls in Science", description: "Promotes full and equal access to science for women and girls.", category: CATEGORIES.SCIENCE, emoji: "🔬" },
  { date: "02-12", name: "Darwin Day", description: "Celebrates Charles Darwin's contributions to evolutionary biology.", category: CATEGORIES.SCIENCE, emoji: "🧬" },
  { date: "02-12", name: "Sexual and Reproductive Health Awareness Day", description: "Promotes awareness of sexual health and reproductive rights.", category: CATEGORIES.HEALTH, emoji: "❤️" },
  { date: "02-13", name: "World Radio Day", description: "Celebrates radio as a medium and promotes its use worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "📻" },
  { date: "02-13", name: "National Women's Day (India)", description: "Birth anniversary of Sarojini Naidu.", category: CATEGORIES.INDIA, emoji: "👩" },
  { date: "02-14", name: "Valentine's Day", description: "A celebration of love and affection.", category: CATEGORIES.CULTURAL, emoji: "❤️" },
  { date: "02-20", name: "World Day of Social Justice", description: "Promotes efforts to tackle poverty, exclusion, gender inequality.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "⚖️" },
  { date: "02-21", name: "International Mother Language Day", description: "Promotes linguistic and cultural diversity and multilingualism.", category: CATEGORIES.INTERNATIONAL, emoji: "🗣️" },
  { date: "02-24", name: "Central Excise Day (India)", description: "Encourages the employees of the excise department.", category: CATEGORIES.INDIA, emoji: "🏢" },
  { date: "02-27", name: "World NGO Day", description: "Celebrates non-governmental organizations globally.", category: CATEGORIES.INTERNATIONAL, emoji: "🤝" },
  { date: "02-28", name: "National Science Day (India)", description: "Celebrates the discovery of the Raman Effect by C.V. Raman.", category: CATEGORIES.SCIENCE, emoji: "🔭" },
  { date: "02-28", name: "Rare Disease Day", description: "Raises awareness for rare diseases and their impact on patients' lives.", category: CATEGORIES.HEALTH, emoji: "🧬" },

  // ── MARCH ──
  { date: "03-01", name: "Zero Discrimination Day", description: "Promotes equality before the law and in practice for everyone.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "✊" },
  { date: "03-01", name: "World Civil Defence Day", description: "Promotes awareness of civil defence and emergency preparedness.", category: CATEGORIES.WORLD, emoji: "🛡️" },
  { date: "03-03", name: "World Wildlife Day", description: "Celebrates and raises awareness of wild animals and plants.", category: CATEGORIES.ENVIRONMENT, emoji: "🐾" },
  { date: "03-03", name: "World Hearing Day", description: "Awareness of deafness prevention.", category: CATEGORIES.HEALTH, emoji: "👂" },
  { date: "03-04", name: "National Safety Day (India)", description: "Promotes safety and accident prevention.", category: CATEGORIES.INDIA, emoji: "⛑️" },
  { date: "03-08", name: "International Women's Day", description: "Celebrates women's achievements and promotes gender equality.", category: CATEGORIES.INTERNATIONAL, emoji: "♀️" },
  { date: "03-10", name: "CISF Raising Day", description: "Central Industrial Security Force foundation day in India.", category: CATEGORIES.INDIA, emoji: "🛡️" },
  { date: "03-12", name: "World Kidney Day", description: "Raises awareness about the importance of kidneys.", category: CATEGORIES.HEALTH, emoji: "🫘" },
  { date: "03-14", name: "Pi Day", description: "Celebrates the mathematical constant π (3.14...).", category: CATEGORIES.SCIENCE, emoji: "π" },
  { date: "03-15", name: "World Consumer Rights Day", description: "Raises global awareness about consumer rights.", category: CATEGORIES.WORLD, emoji: "🛒" },
  { date: "03-16", name: "National Immunization Day (India)", description: "Focuses on the importance of vaccination to protect children.", category: CATEGORIES.HEALTH, emoji: "💉" },
  { date: "03-20", name: "International Day of Happiness", description: "UN day recognizing happiness as a fundamental human goal.", category: CATEGORIES.INTERNATIONAL, emoji: "😊" },
  { date: "03-20", name: "World Sparrow Day", description: "Raises awareness of the house sparrow and other common birds.", category: CATEGORIES.ENVIRONMENT, emoji: "🐦" },
  { date: "03-21", name: "International Day of Forests", description: "Highlights importance of woodlands and trees.", category: CATEGORIES.ENVIRONMENT, emoji: "🌲" },
  { date: "03-21", name: "World Down Syndrome Day", description: "Raises awareness of Down syndrome and supports people with it.", category: CATEGORIES.HEALTH, emoji: "🧡" },
  { date: "03-21", name: "World Poetry Day", description: "Celebrates poetry and its unique ability to capture the human spirit.", category: CATEGORIES.CULTURAL, emoji: "📜" },
  { date: "03-22", name: "World Water Day", description: "Highlights the importance of freshwater and sustainable management.", category: CATEGORIES.ENVIRONMENT, emoji: "💧" },
  { date: "03-23", name: "World Meteorological Day", description: "Marks establishment of World Meteorological Organization.", category: CATEGORIES.WORLD, emoji: "🌤️" },
  { date: "03-23", name: "Martyrs' Day (Shaheed Diwas)", description: "Anniversary of the martyrdom of Bhagat Singh, Sukhdev, and Rajguru.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "03-24", name: "World Tuberculosis Day", description: "Raises awareness about tuberculosis.", category: CATEGORIES.HEALTH, emoji: "🫁" },
  { date: "03-27", name: "World Theatre Day", description: "Celebrates theatre arts.", category: CATEGORIES.CULTURAL, emoji: "🎭" },

  // ── APRIL ──
  { date: "04-01", name: "April Fools' Day", description: "A day of practical jokes and hoaxes.", category: CATEGORIES.CULTURAL, emoji: "🤡" },
  { date: "04-01", name: "Utkal Diwas (Odisha Day)", description: "Formation of Odisha state.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "04-02", name: "World Autism Awareness Day", description: "Promotes understanding of autism spectrum disorder.", category: CATEGORIES.HEALTH, emoji: "💙" },
  { date: "04-04", name: "International Day for Mine Awareness", description: "Promotes efforts to clear landmines.", category: CATEGORIES.INTERNATIONAL, emoji: "⚠️" },
  { date: "04-05", name: "National Maritime Day (India)", description: "Celebrates India's maritime sector.", category: CATEGORIES.INDIA, emoji: "🚢" },
  { date: "04-07", name: "World Health Day", description: "Draws attention to global health issues.", category: CATEGORIES.HEALTH, emoji: "🏥" },
  { date: "04-10", name: "World Homeopathy Day", description: "Celebrates homeopathy.", category: CATEGORIES.HEALTH, emoji: "🌿" },
  { date: "04-11", name: "National Safe Motherhood Day (India)", description: "Maternal health and safe delivery awareness.", category: CATEGORIES.INDIA, emoji: "🤰" },
  { date: "04-13", name: "Jallianwala Bagh Massacre Day", description: "Honoring martyrs of the 1919 massacre.", category: CATEGORIES.INDIA, emoji: "🙏" },
  { date: "04-14", name: "B.R. Ambedkar Remembrance Day", description: "Birth anniversary of Dr. B.R. Ambedkar.", category: CATEGORIES.INDIA, emoji: "📖" },
  { date: "04-17", name: "World Haemophilia Day", description: "Raises awareness about hemophilia.", category: CATEGORIES.HEALTH, emoji: "🩸" },
  { date: "04-18", name: "World Heritage Day", description: "Promotes awareness of world cultural heritage.", category: CATEGORIES.WORLD, emoji: "🏛️" },
  { date: "04-19", name: "World Liver Day", description: "Informs people about liver health.", category: CATEGORIES.HEALTH, emoji: "🧡" },
  { date: "04-21", name: "National Civil Services Day (India)", description: "Honours Indian civil servants.", category: CATEGORIES.INDIA, emoji: "🎖️" },
  { date: "04-22", name: "World Earth Day", description: "Annual event for environmental protection.", category: CATEGORIES.ENVIRONMENT, emoji: "🌍" },
  { date: "04-23", name: "World Book and Copyright Day", description: "Promotes reading and publishing.", category: CATEGORIES.EDUCATION, emoji: "📚" },
  { date: "04-24", name: "National Panchayati Raj Day (India)", description: "Marks the decentralization of power.", category: CATEGORIES.INDIA, emoji: "🏛️" },
  { date: "04-25", name: "World Malaria Day", description: "Global efforts to control malaria.", category: CATEGORIES.HEALTH, emoji: "🦟" },
  { date: "04-26", name: "World Intellectual Property Day", description: "IP rights awareness.", category: CATEGORIES.INTERNATIONAL, emoji: "💡" },
  { date: "04-29", name: "International Dance Day", description: "Celebrates dance worldwide.", category: CATEGORIES.CULTURAL, emoji: "💃" },

  // ── MAY ──
  { date: "05-01", name: "International Labour Day", description: "Celebrates workers worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "⚒️" },
  { date: "05-01", name: "Maharashtra Day & Gujarat Day", description: "State formations of Maharashtra and Gujarat.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "05-03", name: "World Press Freedom Day", description: "Advocates for freedom of the press.", category: CATEGORIES.WORLD, emoji: "📰" },
  { date: "05-04", name: "Coal Miners' Day", description: "Honoring the hard labor of coal miners.", category: CATEGORIES.INTERNATIONAL, emoji: "⛏️" },
  { date: "05-08", name: "World Red Cross Day", description: "Celebrates the humanitarian Red Cross movement.", category: CATEGORIES.WORLD, emoji: "🔴" },
  { date: "05-08", name: "World Thalassemia Day", description: "Thalassemia genetic disorder awareness.", category: CATEGORIES.HEALTH, emoji: "🩸" },
  { date: "05-11", name: "National Technology Day (India)", description: "Marks India's successful nuclear tests in 1998.", category: CATEGORIES.INDIA, emoji: "⚛️" },
  { date: "05-12", name: "International Nurses Day", description: "Celebrates Florence Nightingale's birthday.", category: CATEGORIES.HEALTH, emoji: "👩‍⚕️" },
  { date: "05-15", name: "International Day of Families", description: "Family welfare globally.", category: CATEGORIES.INTERNATIONAL, emoji: "👨‍👩‍👧‍👦" },
  { date: "05-17", name: "World Telecommunication Day", description: "Promotes internet and communication awareness.", category: CATEGORIES.SCIENCE, emoji: "📡" },
  { date: "05-17", name: "World Hypertension Day", description: "High blood pressure awareness.", category: CATEGORIES.HEALTH, emoji: "🩺" },
  { date: "05-18", name: "International Museum Day", description: "Role of museums in cultural exchange.", category: CATEGORIES.CULTURAL, emoji: "🏛️" },
  { date: "05-20", name: "World Bee Day", description: "Importance of bees for food security.", category: CATEGORIES.ENVIRONMENT, emoji: "🐝" },
  { date: "05-21", name: "Anti-Terrorism Day (India)", description: "Marks the death anniversary of Rajiv Gandhi.", category: CATEGORIES.INDIA, emoji: "🕊️" },
  { date: "05-22", name: "International Day for Biological Diversity", description: "Biodiversity awareness.", category: CATEGORIES.ENVIRONMENT, emoji: "🦋" },
  { date: "05-28", name: "Menstrual Hygiene Day", description: "Breaking the taboo and promoting menstrual health.", category: CATEGORIES.HEALTH, emoji: "🩸" },
  { date: "05-31", name: "Anti-Tobacco Day", description: "Encourages abstinence from tobacco.", category: CATEGORIES.HEALTH, emoji: "🚭" },

  // ── JUNE ──
  { date: "06-01", name: "World Milk Day", description: "Dairy sector awareness.", category: CATEGORIES.WORLD, emoji: "🥛" },
  { date: "06-01", name: "Global Day of Parents", description: "Honors parents globally.", category: CATEGORIES.INTERNATIONAL, emoji: "👨‍👩‍👧" },
  { date: "06-03", name: "World Bicycle Day", description: "Sustainable transport.", category: CATEGORIES.WORLD, emoji: "🚴" },
  { date: "06-05", name: "World Environment Day", description: "UN day for environmental protection.", category: CATEGORIES.ENVIRONMENT, emoji: "🌱" },
  { date: "06-07", name: "World Food Safety Day", description: "Foodborne risks prevention.", category: CATEGORIES.HEALTH, emoji: "🥗" },
  { date: "06-08", name: "World Oceans Day", description: "Marine life conservation.", category: CATEGORIES.ENVIRONMENT, emoji: "🌊" },
  { date: "06-08", name: "World Brain Tumor Day", description: "Brain tumor awareness.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "06-12", name: "World Day Against Child Labour", description: "Ending child labour.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🚫" },
  { date: "06-14", name: "World Blood Donor Day", description: "Safe blood awareness.", category: CATEGORIES.HEALTH, emoji: "🩸" },
  { date: "06-15", name: "World Elder Abuse Awareness Day", description: "Promotes actions to prevent elder abuse.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "👴" },
  { date: "06-20", name: "World Refugee Day", description: "Honours refugees globally.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🏕️" },
  { date: "06-21", name: "International Yoga Day", description: "Universal benefits of yoga.", category: CATEGORIES.INTERNATIONAL, emoji: "🧘" },
  { date: "06-21", name: "World Music Day", description: "Free public music concerts.", category: CATEGORIES.CULTURAL, emoji: "🎵" },
  { date: "06-23", name: "International Olympic Day", description: "Promotes the Olympic movement.", category: CATEGORIES.INTERNATIONAL, emoji: "🏅" },
  { date: "06-26", name: "International Day Against Drug Abuse", description: "Drug abuse awareness.", category: CATEGORIES.INTERNATIONAL, emoji: "🚫" },
  { date: "06-29", name: "National Statistics Day (India)", description: "P.C. Mahalanobis' birthday.", category: CATEGORIES.INDIA, emoji: "📊" },

  // ── JULY ──
  { date: "07-01", name: "National Doctor's Day (India)", description: "Tribute to Dr. Bidhan Chandra Roy.", category: CATEGORIES.INDIA, emoji: "👨‍⚕️" },
  { date: "07-01", name: "Chartered Accountants Day (India)", description: "Marks the foundation of ICAI.", category: CATEGORIES.INDIA, emoji: "📊" },
  { date: "07-11", name: "World Population Day", description: "Population issues globally.", category: CATEGORIES.WORLD, emoji: "👥" },
  { date: "07-12", name: "World Malala Day", description: "Advocacy for girls' education.", category: CATEGORIES.EDUCATION, emoji: "📚" },
  { date: "07-15", name: "World Youth Skills Day", description: "Equipping youth with vocational skills.", category: CATEGORIES.EDUCATION, emoji: "🎓" },
  { date: "07-17", name: "World Day for International Justice", description: "Promotes international criminal justice.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "⚖️" },
  { date: "07-18", name: "Nelson Mandela International Day", description: "Mandela's contributions to humanity.", category: CATEGORIES.INTERNATIONAL, emoji: "✊" },
  { date: "07-26", name: "Kargil Vijay Diwas (India)", description: "Victory in the Kargil War.", category: CATEGORIES.INDIA, emoji: "🎖️" },
  { date: "07-28", name: "World Hepatitis Day", description: "Viral hepatitis awareness.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "07-28", name: "World Nature Conservation Day", description: "Preserving a healthy environment.", category: CATEGORIES.ENVIRONMENT, emoji: "🌳" },
  { date: "07-29", name: "International Tiger Day", description: "Global tiger conservation.", category: CATEGORIES.ENVIRONMENT, emoji: "🐯" },

  // ── AUGUST ──
  { date: "08-01", name: "World Lung Cancer Day", description: "Lung cancer awareness.", category: CATEGORIES.HEALTH, emoji: "🫁" },
  { date: "08-06", name: "Hiroshima Day", description: "Commemorates the atomic bombing; promotes peace.", category: CATEGORIES.INTERNATIONAL, emoji: "🕊️" },
  { date: "08-07", name: "National Handloom Day (India)", description: "Promotes handloom weaving craft.", category: CATEGORIES.INDIA, emoji: "🧵" },
  { date: "08-09", name: "Quit India Movement Day", description: "Marks the 1942 movement.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "08-09", name: "Nagasaki Day", description: "Nuclear awareness and peace.", category: CATEGORIES.INTERNATIONAL, emoji: "🕊️" },
  { date: "08-10", name: "World Lion Day", description: "Lion conservation.", category: CATEGORIES.ENVIRONMENT, emoji: "🦁" },
  { date: "08-12", name: "International Youth Day", description: "Youth well-being.", category: CATEGORIES.INTERNATIONAL, emoji: "⚡" },
  { date: "08-12", name: "World Elephant Day", description: "Elephant conservation.", category: CATEGORIES.ENVIRONMENT, emoji: "🐘" },
  { date: "08-13", name: "World Organ Donation Day", description: "Encouraging organ donation.", category: CATEGORIES.HEALTH, emoji: "🫀" },
  { date: "08-15", name: "Independence Day (India)", description: "Celebrates India's independence.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "08-19", name: "World Photography Day", description: "Photography celebration.", category: CATEGORIES.CULTURAL, emoji: "📸" },
  { date: "08-19", name: "World Humanitarian Day", description: "Honoring humanitarians.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🤝" },
  { date: "08-20", name: "Sadbhavana Diwas (India)", description: "Birth anniversary of Rajiv Gandhi.", category: CATEGORIES.INDIA, emoji: "🕊️" },
  { date: "08-26", name: "Women's Equality Day", description: "Women's rights.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "⚖️" },
  { date: "08-29", name: "National Sports Day (India)", description: "Dhyan Chand's birthday.", category: CATEGORIES.INDIA, emoji: "🏑" },

  // ── SEPTEMBER ──
  { date: "09-02", name: "World Coconut Day", description: "Coconut cultivation benefits.", category: CATEGORIES.WORLD, emoji: "🥥" },
  { date: "09-05", name: "Teachers' Day (India)", description: "Honors Dr. Sarvepalli Radhakrishnan.", category: CATEGORIES.INDIA, emoji: "👨‍🏫" },
  { date: "09-05", name: "International Day of Charity", description: "Promoting charitable activities.", category: CATEGORIES.INTERNATIONAL, emoji: "💝" },
  { date: "09-08", name: "International Literacy Day", description: "Importance of literacy.", category: CATEGORIES.EDUCATION, emoji: "📖" },
  { date: "09-10", name: "World Suicide Prevention Day", description: "Mental health and suicide prevention awareness.", category: CATEGORIES.HEALTH, emoji: "💚" },
  { date: "09-14", name: "Hindi Diwas (India)", description: "Hindi as an official language.", category: CATEGORIES.INDIA, emoji: "🗣️" },
  { date: "09-15", name: "International Day of Democracy", description: "Democratic values globally.", category: CATEGORIES.INTERNATIONAL, emoji: "🗳️" },
  { date: "09-15", name: "Engineers' Day (India)", description: "Sir M. Visvesvaraya's birthday.", category: CATEGORIES.INDIA, emoji: "⚙️" },
  { date: "09-16", name: "World Ozone Day", description: "Ozone layer preservation.", category: CATEGORIES.ENVIRONMENT, emoji: "🌐" },
  { date: "09-21", name: "International Day of Peace", description: "Global ceasefire and non-violence.", category: CATEGORIES.INTERNATIONAL, emoji: "🕊️" },
  { date: "09-21", name: "World Alzheimer's Day", description: "Dementia awareness.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "09-25", name: "Antyodaya Diwas", description: "Pt. Deen Dayal Upadhyaya Jayanti.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "09-27", name: "World Tourism Day", description: "Importance of tourism.", category: CATEGORIES.WORLD, emoji: "✈️" },
  { date: "09-28", name: "World Rabies Day", description: "Rabies prevention.", category: CATEGORIES.HEALTH, emoji: "🐕‍🦺" },
  { date: "09-29", name: "World Heart Day", description: "Cardiovascular health.", category: CATEGORIES.HEALTH, emoji: "❤️" },

  // ── OCTOBER ──
  { date: "10-01", name: "International Day of Older Persons", description: "Ageing populations awareness.", category: CATEGORIES.INTERNATIONAL, emoji: "👴" },
  { date: "10-01", name: "International Coffee Day", description: "Celebrates coffee and fair trade.", category: CATEGORIES.CULTURAL, emoji: "☕" },
  { date: "10-02", name: "Gandhi Jayanti (India) / Int. Day of Non-Violence", description: "Birthday of Mahatma Gandhi.", category: CATEGORIES.INDIA, emoji: "🙏" },
  { date: "10-02", name: "Lal Bahadur Shastri Jayanti", description: "Birth anniversary of India's 2nd Prime Minister.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "10-04", name: "World Animal Welfare Day", description: "Animal rights.", category: CATEGORIES.ENVIRONMENT, emoji: "🐾" },
  { date: "10-05", name: "World Teachers' Day", description: "Teaching profession worldwide.", category: CATEGORIES.EDUCATION, emoji: "👩‍🏫" },
  { date: "10-08", name: "Indian Air Force Day", description: "Air force establishment.", category: CATEGORIES.INDIA, emoji: "✈️" },
  { date: "10-09", name: "World Post Day", description: "Universal Postal Union anniversary.", category: CATEGORIES.WORLD, emoji: "📭" },
  { date: "10-10", name: "World Mental Health Day", description: "Mental health care and advocacy.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "10-11", name: "International Day of the Girl Child", description: "Girls' rights awareness.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "👧" },
  { date: "10-15", name: "World Students' Day", description: "Dr. A.P.J. Abdul Kalam's birthday.", category: CATEGORIES.EDUCATION, emoji: "🎓" },
  { date: "10-16", name: "World Food Day", description: "Global food security.", category: CATEGORIES.WORLD, emoji: "🍽️" },
  { date: "10-24", name: "United Nations Day", description: "UN Charter entry into force.", category: CATEGORIES.INTERNATIONAL, emoji: "🌐" },
  { date: "10-24", name: "World Polio Day", description: "Polio-free world efforts.", category: CATEGORIES.HEALTH, emoji: "💊" },
  { date: "10-31", name: "National Unity Day (Rashtriya Ekta Diwas)", description: "Sardar Vallabhbhai Patel's birth anniversary.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },

  // ── NOVEMBER ──
  { date: "11-01", name: "World Vegan Day", description: "Plant-based lifestyle promotion.", category: CATEGORIES.WORLD, emoji: "🌱" },
  { date: "11-05", name: "World Tsunami Awareness Day", description: "Tsunami risk reduction.", category: CATEGORIES.WORLD, emoji: "🌊" },
  { date: "11-07", name: "National Cancer Awareness Day (India)", description: "Cancer prevention.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "11-09", name: "Legal Services Day", description: "Free legal aid awareness.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "⚖️" },
  { date: "11-11", name: "National Education Day (India)", description: "Maulana Abul Kalam Azad's birthday.", category: CATEGORIES.INDIA, emoji: "📚" },
  { date: "11-12", name: "World Pneumonia Day", description: "Pneumonia awareness.", category: CATEGORIES.HEALTH, emoji: "🫁" },
  { date: "11-14", name: "Children's Day (India)", description: "Jawaharlal Nehru's birthday.", category: CATEGORIES.INDIA, emoji: "🎈" },
  { date: "11-14", name: "World Diabetes Day", description: "Diabetes awareness globally.", category: CATEGORIES.HEALTH, emoji: "🩺" },
  { date: "11-16", name: "National Press Day (India)", description: "Press Council of India establishment.", category: CATEGORIES.INDIA, emoji: "📰" },
  { date: "11-19", name: "World Toilet Day", description: "Sanitation crisis awareness.", category: CATEGORIES.WORLD, emoji: "🚽" },
  { date: "11-20", name: "Universal Children's Day", description: "Children worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "👦" },
  { date: "11-21", name: "World Television Day", description: "Impact of television.", category: CATEGORIES.SCIENCE, emoji: "📺" },
  { date: "11-26", name: "Constitution Day (Samvidhan Diwas)", description: "Adoption of India's Constitution.", category: CATEGORIES.INDIA, emoji: "📜" },
  { date: "11-26", name: "National Milk Day (India)", description: "Dr. Verghese Kurien's birth.", category: CATEGORIES.INDIA, emoji: "🥛" },

  // ── DECEMBER ──
  { date: "12-01", name: "World AIDS Day", description: "AIDS pandemic awareness.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "12-02", name: "National Pollution Control Day (India)", description: "Pollution prevention.", category: CATEGORIES.ENVIRONMENT, emoji: "🌿" },
  { date: "12-03", name: "World Day of Persons with Disabilities", description: "Rights of PwD.", category: CATEGORIES.WORLD, emoji: "♿" },
  { date: "12-04", name: "Indian Navy Day", description: "Navy contributions.", category: CATEGORIES.INDIA, emoji: "⚓" },
  { date: "12-05", name: "World Soil Day", description: "Healthy soil management.", category: CATEGORIES.ENVIRONMENT, emoji: "🌱" },
  { date: "12-07", name: "Armed Forces Flag Day (India)", description: "Honoring soldiers.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "12-09", name: "International Anti-Corruption Day", description: "Anti-corruption measures.", category: CATEGORIES.INTERNATIONAL, emoji: "🚫" },
  { date: "12-10", name: "Human Rights Day", description: "Universal Declaration of Human Rights.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "✊" },
  { date: "12-11", name: "International Mountain Day", description: "Mountain sustainability.", category: CATEGORIES.ENVIRONMENT, emoji: "⛰️" },
  { date: "12-14", name: "National Energy Conservation Day (India)", description: "Energy efficiency.", category: CATEGORIES.INDIA, emoji: "⚡" },
  { date: "12-16", name: "Vijay Diwas (India)", description: "Victory over Pakistan in 1971.", category: CATEGORIES.INDIA, emoji: "🎖️" },
  { date: "12-18", name: "Minorities Rights Day (India)", description: "Protecting minority rights.", category: CATEGORIES.INDIA, emoji: "🤝" },
  { date: "12-18", name: "International Migrants Day", description: "Migrants' rights.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🚶" },
  { date: "12-22", name: "National Mathematics Day (India)", description: "Srinivasa Ramanujan's birthday.", category: CATEGORIES.INDIA, emoji: "🔢" },
  { date: "12-23", name: "Kisan Diwas (National Farmers' Day)", description: "Chaudhary Charan Singh's birthday.", category: CATEGORIES.INDIA, emoji: "🌾" },
  { date: "12-24", name: "National Consumer Rights Day (India)", description: "Consumer rights in India.", category: CATEGORIES.INDIA, emoji: "🛒" },
  { date: "12-25", name: "Good Governance Day (India)", description: "Atal Bihari Vajpayee's birthday.", category: CATEGORIES.INDIA, emoji: "🏛️" },
  { date: "12-25", name: "Christmas Day", description: "Birth of Jesus Christ.", category: CATEGORIES.FESTIVAL, emoji: "🎄" }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CATEGORIES, importantDays };
}
