// Important Days Database – expanded with festivals
// Format: { date: "MM-DD", name, description, category, emoji }

const CATEGORIES = {
  INTERNATIONAL: "International",
  WORLD: "World Day",
  HEALTH: "Health",
  ENVIRONMENT: "Environment",
  INDIA: "India National",
  FESTIVAL: "Festival",
  RELIGIOUS: "Religious",
  CULTURAL: "Cultural",
  SCIENCE: "Science & Tech",
  HUMAN_RIGHTS: "Human Rights",
  EDUCATION: "Education",
};

const importantDays = [
  // ── JANUARY ──
  { date: "01-01", name: "New Year's Day", description: "The first day of the Gregorian calendar year, celebrated worldwide with joy and fireworks.", category: CATEGORIES.CULTURAL, emoji: "🎆" },
  { date: "01-04", name: "World Braille Day", description: "Honors Louis Braille, inventor of the Braille system for visually impaired people.", category: CATEGORIES.INTERNATIONAL, emoji: "👁️" },
  { date: "01-06", name: "World Day of War Orphans", description: "Raises awareness about difficulties faced by orphans of war worldwide.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🕊️" },
  { date: "01-09", name: "NRI Day (Pravasi Bharatiya Divas)", description: "Celebrates contributions of overseas Indian community to India.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "01-10", name: "World Hindi Day", description: "Commemorates the anniversary of the first World Hindi Conference in 1975.", category: CATEGORIES.INDIA, emoji: "🗣️" },
  { date: "01-12", name: "National Youth Day (India)", description: "Celebrates Swami Vivekananda's birthday. Theme: youth empowerment.", category: CATEGORIES.INDIA, emoji: "⚡" },
  { date: "01-13", name: "Lohri", description: "Punjabi winter harvest festival celebrated with bonfires, dancing and sweets.", category: CATEGORIES.FESTIVAL, emoji: "🔥" },
  { date: "01-14", name: "Makar Sankranti", description: "Hindu harvest festival marking the sun's transit into Capricorn. Celebrated as Pongal in Tamil Nadu.", category: CATEGORIES.FESTIVAL, emoji: "☀️" },
  { date: "01-14", name: "Pongal", description: "Tamil harvest festival; four-day celebration with sugarcane, rice dishes and kolam art.", category: CATEGORIES.FESTIVAL, emoji: "🌾" },
  { date: "01-15", name: "Indian Army Day", description: "Celebrates the Indian Army and its contributions to the nation.", category: CATEGORIES.INDIA, emoji: "🎖️" },
  { date: "01-24", name: "National Girl Child Day (India)", description: "Promotes rights and welfare of girl children in India.", category: CATEGORIES.INDIA, emoji: "👧" },
  { date: "01-25", name: "National Voters' Day (India)", description: "Encourages new voters to participate in the democratic process.", category: CATEGORIES.INDIA, emoji: "🗳️" },
  { date: "01-26", name: "Republic Day of India", description: "India's constitution came into effect on this day in 1950. Grand parade at Rajpath, New Delhi.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "01-27", name: "International Holocaust Remembrance Day", description: "UN day to honor victims of the Holocaust during WWII.", category: CATEGORIES.INTERNATIONAL, emoji: "🕯️" },
  { date: "01-28", name: "Data Privacy Day", description: "Raises awareness about online privacy and data protection.", category: CATEGORIES.SCIENCE, emoji: "🔐" },
  { date: "01-30", name: "Martyrs' Day (India)", description: "Commemorates the assassination of Mahatma Gandhi in 1948.", category: CATEGORIES.INDIA, emoji: "🙏" },
  { date: "01-30", name: "World Neglected Tropical Diseases Day", description: "Raises awareness about tropical diseases that disproportionately affect the world's poorest populations.", category: CATEGORIES.HEALTH, emoji: "🪰" },
  { date: "01-30", name: "World Leprosy Day", description: "Promotes understanding of leprosy and support for those affected. Celebrated on Jan 30 in India.", category: CATEGORIES.HEALTH, emoji: "🏥" },

  // ── FEBRUARY ──
  { date: "02-02", name: "World Wetlands Day", description: "Marks the adoption of the Ramsar Convention on Wetlands in 1971.", category: CATEGORIES.ENVIRONMENT, emoji: "🌿" },
  { date: "02-04", name: "World Cancer Day", description: "International awareness and education day about cancer prevention and treatment.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "02-05", name: "Safer Internet Day", description: "Promotes safer and more responsible use of online technology worldwide.", category: CATEGORIES.SCIENCE, emoji: "🌐" },
  { date: "02-09", name: "International Epilepsy Day", description: "Focuses on raising awareness and reducing the stigma of epilepsy globally.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "02-10", name: "World Pulses Day", description: "Celebrates the nutritional and environmental benefits of pulses.", category: CATEGORIES.WORLD, emoji: "🌾" },
  { date: "02-11", name: "International Day of Women and Girls in Science", description: "Promotes full and equal access to science for women and girls.", category: CATEGORIES.SCIENCE, emoji: "🔬" },
  { date: "02-12", name: "Sexual and Reproductive Health Awareness Day", description: "Promotes awareness of sexual health and reproductive rights.", category: CATEGORIES.HEALTH, emoji: "❤️" },
  { date: "02-13", name: "World Radio Day", description: "Celebrates radio as a medium and promotes its use worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "📻" },
  { date: "02-14", name: "Valentine's Day", description: "A celebration of love and affection between people, marked with cards, gifts and flowers.", category: CATEGORIES.CULTURAL, emoji: "❤️" },
  { date: "02-18", name: "Guru Ravidas Jayanti", description: "Birth anniversary of Sant Guru Ravidas, celebrated across Punjab and Haryana.", category: CATEGORIES.FESTIVAL, emoji: "🙏" },
  { date: "02-20", name: "World Day of Social Justice", description: "Promotes efforts to tackle poverty, exclusion, gender inequality and unemployment.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "⚖️" },
  { date: "02-21", name: "International Mother Language Day", description: "Promotes linguistic and cultural diversity and multilingualism.", category: CATEGORIES.INTERNATIONAL, emoji: "🗣️" },
  { date: "02-23", name: "World Peace and Understanding Day", description: "Celebrates Rotary International's founding and promotion of world peace.", category: CATEGORIES.WORLD, emoji: "🕊️" },
  { date: "02-15", name: "Maha Shivaratri", description: "Hindu festival honoring Lord Shiva — a night of prayer, fasting and devotion. Chaturdashi Tithi begins on Feb 15 at 05:04 PM (2026).", category: CATEGORIES.FESTIVAL, emoji: "🔱" },
  { date: "02-15", name: "International Childhood Cancer Day", description: "A global collaborative campaign to raise awareness about childhood cancer.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "02-28", name: "National Science Day (India)", description: "Celebrates the discovery of the Raman Effect by C.V. Raman in 1928.", category: CATEGORIES.SCIENCE, emoji: "🔭" },
  { date: "02-28", name: "Rare Disease Day", description: "Raises awareness for rare diseases and their impact on patients' lives.", category: CATEGORIES.HEALTH, emoji: "🧬" },

  // ── MARCH ──
  { date: "03-01", name: "Zero Discrimination Day", description: "Promotes equality before the law and in practice for everyone worldwide.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "✊" },
  { date: "03-01", name: "World Civil Defence Day", description: "Promotes awareness of civil defence and emergency preparedness worldwide.", category: CATEGORIES.WORLD, emoji: "🛡️" },
  { date: "03-02", name: "World Teen Mental Wellness Day", description: "Raises awareness about teen mental health and encourages young people to seek help and support.", category: CATEGORIES.HEALTH, emoji: "💚" },
  { date: "03-03", name: "World Hearing Day", description: "WHO's annual day promoting hearing care and raising awareness about hearing loss prevention.", category: CATEGORIES.HEALTH, emoji: "👂" },
  { date: "03-03", name: "Holika Dahan (Holi Eve)", description: "Bonfire night before Holi — burning of Holika symbolising victory of good over evil.", category: CATEGORIES.FESTIVAL, emoji: "🔥" },
  { date: "03-04", name: "Holi – Festival of Colors", description: "Vibrant Hindu spring festival celebrated with colors, water, sweets and music. One of India's most joyful festivals.", category: CATEGORIES.FESTIVAL, emoji: "🎨" },
  { date: "03-03", name: "World Wildlife Day", description: "Celebrates and raises awareness of wild animals and plants worldwide.", category: CATEGORIES.ENVIRONMENT, emoji: "🐾" },
  { date: "03-04", name: "World Obesity Day", description: "Aims to raise awareness and improve the understanding of the root causes of obesity.", category: CATEGORIES.HEALTH, emoji: "🍎" },
  { date: "03-04", name: "National Safety Day (India)", description: "Promotes safety and accident prevention across India.", category: CATEGORIES.INDIA, emoji: "⛑️" },
  { date: "03-08", name: "International Women's Day", description: "Celebrates women's achievements and promotes gender equality globally.", category: CATEGORIES.INTERNATIONAL, emoji: "♀️" },
  { date: "03-12", name: "World Kidney Day", description: "Raises awareness about the importance of kidneys and reducing the impact of kidney diseases.", category: CATEGORIES.HEALTH, emoji: "🫘" },
  { date: "03-14", name: "World Sleep Day", description: "Annual event celebrating the importance of healthy sleep and raising awareness of sleep disorders.", category: CATEGORIES.HEALTH, emoji: "😴" },
  { date: "03-16", name: "National Immunization Day (India)", description: "Focuses on the importance of vaccination to protect children from diseases like Polio.", category: CATEGORIES.HEALTH, emoji: "💉" },
  { date: "03-14", name: "Pi Day", description: "Celebrates the mathematical constant π (3.14...) with math activities and pie.", category: CATEGORIES.SCIENCE, emoji: "π" },
  { date: "03-15", name: "World Consumer Rights Day", description: "Raises global awareness about consumer rights and needs.", category: CATEGORIES.WORLD, emoji: "🛒" },
  { date: "03-19", name: "Chaitra Navratri Begins", description: "Nine-night Hindu festival celebrating Goddess Durga — fasting, prayers and Garba dance.", category: CATEGORIES.FESTIVAL, emoji: "🌸" },
  { date: "03-20", name: "International Day of Happiness", description: "UN day recognizing happiness as a fundamental human goal.", category: CATEGORIES.INTERNATIONAL, emoji: "😊" },
  { date: "03-20", name: "World Oral Health Day", description: "Raises global awareness of the issues around oral health and the importance of oral hygiene.", category: CATEGORIES.HEALTH, emoji: "🦷" },
  { date: "03-21", name: "Eid al-Fitr", description: "Marks the end of Ramadan — a joyous Islamic celebration of prayer, feast and togetherness. (Tentative, subject to moon sighting.)", category: CATEGORIES.FESTIVAL, emoji: "🌙" },
  { date: "03-21", name: "World Down Syndrome Day", description: "Raises awareness of Down syndrome and supports people with it.", category: CATEGORIES.HEALTH, emoji: "🧡" },
  { date: "03-21", name: "World Poetry Day", description: "Celebrates poetry and its unique ability to capture the creative spirit.", category: CATEGORIES.CULTURAL, emoji: "📜" },
  { date: "03-22", name: "World Water Day", description: "Highlights the importance of freshwater and advocates for sustainable management.", category: CATEGORIES.ENVIRONMENT, emoji: "💧" },
  { date: "03-23", name: "World Meteorological Day", description: "Marks establishment of World Meteorological Organization in 1950.", category: CATEGORIES.WORLD, emoji: "🌤️" },
  { date: "03-24", name: "World Tuberculosis Day", description: "Raises awareness about tuberculosis and efforts to end the epidemic.", category: CATEGORIES.HEALTH, emoji: "🫁" },
  { date: "03-26", name: "Ram Navami", description: "Hindu festival celebrating the birth of Lord Rama — prayers, fasting and temple visits. Official gazetted holiday in India.", category: CATEGORIES.FESTIVAL, emoji: "🏹" },
  { date: "03-31", name: "Mahavir Jayanti", description: "Birth anniversary of Lord Mahavira, 24th Tirthankara of Jainism. Gazetted public holiday in India.", category: CATEGORIES.FESTIVAL, emoji: "🔱" },
  { date: "03-27", name: "World Theatre Day", description: "Celebrates theatre arts and its role in promoting cultural value worldwide.", category: CATEGORIES.CULTURAL, emoji: "🎭" },
  { date: "03-30", name: "World Bipolar Day", description: "Focuses on providing information about bipolar disorders and reducing social stigma.", category: CATEGORIES.HEALTH, emoji: "🧠" },

  // ── APRIL ──
  { date: "04-01", name: "April Fools' Day", description: "A day of practical jokes and hoaxes celebrated globally with laughter.", category: CATEGORIES.CULTURAL, emoji: "🤡" },
  { date: "04-02", name: "World Autism Awareness Day", description: "Promotes understanding and acceptance of autism spectrum disorder.", category: CATEGORIES.HEALTH, emoji: "💙" },
  { date: "04-04", name: "International Day for Mine Awareness", description: "Promotes efforts to clear landmines and help victims worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "⚠️" },
  { date: "04-03", name: "Good Friday", description: "Christian commemoration of the crucifixion of Jesus Christ. Gazetted public holiday in India.", category: CATEGORIES.FESTIVAL, emoji: "✝️" },
  { date: "04-02", name: "Hanuman Jayanti", description: "Birth anniversary of Lord Hanuman — celebrated across India with prayers, fasting and temple visits. In 2026, it falls on April 2nd.", category: CATEGORIES.FESTIVAL, emoji: "🐒" },
  { date: "04-07", name: "World Health Day", description: "Draws attention to global health issues, organized by the World Health Organization.", category: CATEGORIES.HEALTH, emoji: "🏥" },
  { date: "04-10", name: "World Homeopathy Day", description: "Celebrates the birth of Dr. Samuel Hahnemann and the system of homeopathy.", category: CATEGORIES.HEALTH, emoji: "🌿" },
  { date: "04-11", name: "World Parkinson's Disease Day", description: "Raises awareness about Parkinson's disease and its impact on individuals and families.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "04-14", name: "World Chagas Disease Day", description: "Raises awareness about Chagas disease, a neglected tropical disease.", category: CATEGORIES.HEALTH, emoji: "🐞" },
  { date: "04-14", name: "Ambedkar Jayanti (India)", description: "Birth anniversary of Dr. B.R. Ambedkar, father of Indian constitution and champion of Dalits.", category: CATEGORIES.INDIA, emoji: "📖" },
  { date: "04-14", name: "Baisakhi", description: "Punjabi and Sikh harvest festival marking Sikh New Year — celebrated with Bhangra and feasting.", category: CATEGORIES.FESTIVAL, emoji: "🌾" },
  { date: "04-14", name: "Tamil New Year (Puthandu)", description: "Tamil New Year — first day of the Tamil calendar month Chithirai.", category: CATEGORIES.FESTIVAL, emoji: "🎊" },
  { date: "04-17", name: "World Haemophilia Day", description: "Raises awareness about hemophilia and other bleeding disorders.", category: CATEGORIES.HEALTH, emoji: "🩸" },
  { date: "04-19", name: "World Liver Day", description: "Informs people about the importance of the liver and how to prevent liver-related diseases.", category: CATEGORIES.HEALTH, emoji: "🧡" },
  { date: "04-18", name: "World Heritage Day", description: "Promotes awareness of world cultural heritage and its preservation.", category: CATEGORIES.WORLD, emoji: "🏛️" },
  { date: "04-21", name: "Civil Services Day (India)", description: "Honours Indian civil servants who dedicate their life to public service.", category: CATEGORIES.INDIA, emoji: "🎖️" },
  { date: "04-22", name: "Earth Day", description: "Annual event to demonstrate support for environmental protection worldwide.", category: CATEGORIES.ENVIRONMENT, emoji: "🌍" },
  { date: "04-23", name: "World Book and Copyright Day", description: "Promotes reading, publishing and protection of intellectual property.", category: CATEGORIES.EDUCATION, emoji: "📚" },
  { date: "04-25", name: "World Malaria Day", description: "Raises awareness about global efforts to control and reduce malaria.", category: CATEGORIES.HEALTH, emoji: "🦟" },
  { date: "04-24", name: "World Immunization Week Begins", description: "A week-long global campaign to promote the use of vaccines to protect people of all ages against disease.", category: CATEGORIES.HEALTH, emoji: "💉" },
  { date: "04-29", name: "International Dance Day", description: "Celebrates dance and its rich cultural significance worldwide.", category: CATEGORIES.CULTURAL, emoji: "💃" },

  // ── MAY ──
  { date: "05-01", name: "International Workers' Day (Labour Day)", description: "Celebrates labourers and the working class worldwide — a global public holiday.", category: CATEGORIES.INTERNATIONAL, emoji: "⚒️" },
  { date: "05-01", name: "Maharashtra Day (India)", description: "Celebrates formation of Maharashtra state on 1 May 1960.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "05-03", name: "World Press Freedom Day", description: "Advocates for freedom of the press and freedom of expression worldwide.", category: CATEGORIES.WORLD, emoji: "📰" },
  { date: "05-07", name: "Rabindranath Tagore Jayanti", description: "Birthday of Nobel laureate, poet and philosopher Rabindranath Tagore.", category: CATEGORIES.INDIA, emoji: "✍️" },
  { date: "05-08", name: "World Red Cross Day", description: "Celebrates Henri Dunant's birthday and the humanitarian Red Cross movement.", category: CATEGORIES.WORLD, emoji: "🔴" },
  { date: "05-11", name: "National Technology Day (India)", description: "Marks India's successful nuclear tests (Pokhran-II) in 1998.", category: CATEGORIES.INDIA, emoji: "⚛️" },
  { date: "05-05", name: "World Hand Hygiene Day", description: "Highlights the importance of hand hygiene in health care and community settings.", category: CATEGORIES.HEALTH, emoji: "🧼" },
  { date: "05-12", name: "International Nurses Day", description: "Celebrates nurses' contributions to society on Florence Nightingale's birthday.", category: CATEGORIES.HEALTH, emoji: "👩‍⚕️" },
  { date: "05-12", name: "International ME/CFS Awareness Day", description: "Raises awareness about Myalgic Encephalomyelitis/Chronic Fatigue Syndrome.", category: CATEGORIES.HEALTH, emoji: "🔋" },
  { date: "05-23", name: "Buddha Purnima (Vesak)", description: "Celebrates the birth, enlightenment and death of Gautama Buddha. Gazetted public holiday in India. In 2026, it falls on 23 May.", category: CATEGORIES.FESTIVAL, emoji: "☸️" },
  { date: "05-15", name: "International Day of Families", description: "Promotes awareness of issues relating to families and family welfare globally.", category: CATEGORIES.INTERNATIONAL, emoji: "👨‍👩‍👧‍👦" },
  { date: "05-17", name: "World Telecommunication Day", description: "Promotes awareness of the internet and new communication technologies.", category: CATEGORIES.SCIENCE, emoji: "📡" },
  { date: "05-20", name: "World Bee Day", description: "Raises awareness about the importance of bees and beekeeping for food security.", category: CATEGORIES.ENVIRONMENT, emoji: "🐝" },
  { date: "05-22", name: "International Day for Biological Diversity", description: "Celebrates and promotes awareness of biodiversity and ecosystem health.", category: CATEGORIES.ENVIRONMENT, emoji: "🦋" },
  { date: "05-25", name: "Africa Day", description: "Commemorates the founding of the Organisation of African Unity on 25 May 1963.", category: CATEGORIES.INTERNATIONAL, emoji: "🌍" },
  { date: "05-27", name: "Eid al-Adha", description: "Islamic festival of sacrifice honoring Ibrahim's willingness to sacrifice his son — prayers and feasting. (Tentative 2026, moon sighting based.)", category: CATEGORIES.FESTIVAL, emoji: "🐑" },
  { date: "05-17", name: "World Hypertension Day", description: "Raises awareness about high blood pressure and its prevention, detection and control.", category: CATEGORIES.HEALTH, emoji: "🩺" },
  { date: "05-19", name: "World IBD Day", description: "Raises awareness about Crohn's disease and ulcerative colitis (Inflammatory Bowel Disease).", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "05-31", name: "World No Tobacco Day", description: "Encourages people to abstain from tobacco use and promotes health.", category: CATEGORIES.HEALTH, emoji: "🚭" },

  // ── JUNE ──
  { date: "06-01", name: "World Milk Day", description: "Promotes awareness of milk as a global food and the dairy sector.", category: CATEGORIES.WORLD, emoji: "🥛" },
  { date: "06-01", name: "Global Day of Parents", description: "Honors parents and the parental role in nurturing children worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "👨‍👩‍👧" },
  { date: "06-03", name: "World Bicycle Day", description: "Promotes the bicycle as a simple, affordable, clean and sustainable transport mode.", category: CATEGORIES.WORLD, emoji: "🚴" },
  { date: "06-05", name: "World Environment Day", description: "Principal UN day for promoting awareness and action for environmental protection.", category: CATEGORIES.ENVIRONMENT, emoji: "🌱" },
  { date: "06-08", name: "World Oceans Day", description: "Celebrates and promotes conservation of the world's oceans and marine life.", category: CATEGORIES.ENVIRONMENT, emoji: "🌊" },
  { date: "06-12", name: "World Day Against Child Labour", description: "Highlights plight of child labourers and promotes solutions to end the practice.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🚫" },
  { date: "06-13", name: "International Albinism Awareness Day", description: "Celebrates people with albinism and raises awareness about their rights and challenges.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🤍" },
  { date: "06-07", name: "World Food Safety Day", description: "Aims to draw attention and inspire action to help prevent, detect and manage foodborne risks.", category: CATEGORIES.HEALTH, emoji: "🥗" },
  { date: "06-08", name: "World Brain Tumor Day", description: "Raises awareness about brain tumors and honors those affected by the disease.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "06-14", name: "World Blood Donor Day", description: "Raises awareness about the need for safe blood and blood products worldwide.", category: CATEGORIES.HEALTH, emoji: "🩸" },
  { date: "06-19", name: "World Sickle Cell Day", description: "Focuses on raising awareness about sickle cell disease and its impact on individuals and families.", category: CATEGORIES.HEALTH, emoji: "🩸" },
  { date: "06-15", name: "World Elder Abuse Awareness Day", description: "Raises awareness about elder abuse and promotes actions to prevent it globally.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "👴" },
  { date: "06-26", name: "Muharram", description: "Islamic New Year and day of mourning for Imam Hussain's martyrdom at Karbala. Gazetted holiday in India. (Tentative, moon sighting based.)", category: CATEGORIES.FESTIVAL, emoji: "🌙" },
  { date: "06-20", name: "World Refugee Day", description: "Honours refugees around the globe and raises awareness of their situation.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🏕️" },
  { date: "06-21", name: "International Yoga Day", description: "Celebrates yoga and its universal benefits to health and wellbeing — India's initiative.", category: CATEGORIES.INDIA, emoji: "🧘" },
  { date: "06-21", name: "World Music Day (Fête de la Musique)", description: "Free public music concerts held worldwide on the summer solstice.", category: CATEGORIES.CULTURAL, emoji: "🎵" },
  { date: "06-26", name: "International Day Against Drug Abuse", description: "Raises awareness of the major problem that illicit drugs represent worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "🚫" },
  { date: "06-29", name: "National Statistics Day (India)", description: "Celebrates birthday of Prof. P.C. Mahalanobis, pioneer of statistics in India.", category: CATEGORIES.INDIA, emoji: "📊" },

  // ── JULY ──
  { date: "07-01", name: "National Doctor's Day (India)", description: "Pays tribute to Dr. Bidhan Chandra Roy on his birth & death anniversary.", category: CATEGORIES.INDIA, emoji: "👨‍⚕️" },
  { date: "07-06", name: "Guru Purnima", description: "Hindu-Buddhist festival to honor spiritual teachers; disciples offer gratitude to their Gurus.", category: CATEGORIES.FESTIVAL, emoji: "🪔" },
  { date: "07-11", name: "World Population Day", description: "Focuses attention on the urgency and importance of population issues globally.", category: CATEGORIES.WORLD, emoji: "👥" },
  { date: "07-12", name: "Malala Day", description: "Celebrates Malala Yousafzai's birthday and her advocacy for girls' education worldwide.", category: CATEGORIES.EDUCATION, emoji: "📚" },
  { date: "07-15", name: "World Youth Skills Day", description: "Celebrates the strategic importance of equipping youth with vocational skills.", category: CATEGORIES.EDUCATION, emoji: "🎓" },
  { date: "07-18", name: "Nelson Mandela International Day", description: "Celebrates Nelson Mandela's life and his contributions to humanity and peace.", category: CATEGORIES.INTERNATIONAL, emoji: "✊" },
  { date: "07-26", name: "Kargil Vijay Diwas (India)", description: "Celebrates India's victory in the Kargil War with Pakistan in 1999.", category: CATEGORIES.INDIA, emoji: "🎖️" },
  { date: "07-25", name: "World Drowning Prevention Day", description: "Raises global awareness about drowning and promotes water safety measures.", category: CATEGORIES.HEALTH, emoji: "🌊" },
  { date: "07-28", name: "World Hepatitis Day", description: "Raises awareness about viral hepatitis — prevention, testing and treatment.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "07-29", name: "World ORS Day", description: "Promotes the use of Oral Rehydration Salts (ORS) to prevent dehydration caused by diarrhea.", category: CATEGORIES.HEALTH, emoji: "🥤" },
  { date: "07-29", name: "International Tiger Day", description: "Raises awareness for tiger conservation globally.", category: CATEGORIES.ENVIRONMENT, emoji: "🐯" },
  { date: "07-30", name: "International Day of Friendship", description: "Promotes the role of friendship in fostering peace and understanding across cultures.", category: CATEGORIES.INTERNATIONAL, emoji: "🤝" },

  // ── AUGUST ──
  { date: "08-06", name: "Hiroshima Day", description: "Commemorates the first atomic bomb dropped on Hiroshima in 1945; promotes peace.", category: CATEGORIES.INTERNATIONAL, emoji: "🕊️" },
  { date: "08-07", name: "National Handloom Day (India)", description: "Revives and promotes handloom weaving craft in India.", category: CATEGORIES.INDIA, emoji: "🧵" },
  { date: "08-09", name: "Quit India Day (India)", description: "Marks the start of the Quit India Movement under Mahatma Gandhi in 1942.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "08-01", name: "World Lung Cancer Day", description: "Raises awareness about lung cancer and the importance of early detection.", category: CATEGORIES.HEALTH, emoji: "🫁" },
  { date: "08-01", name: "World Breastfeeding Week Begins", description: "A global campaign to raise awareness about breastfeeding and its benefits for babies.", category: CATEGORIES.HEALTH, emoji: "🤱" },
  { date: "08-12", name: "International Youth Day", description: "Celebrates youth and promotes actions to improve their well-being worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "⚡" },
  { date: "08-12", name: "World Elephant Day", description: "Raises awareness about the care and conservation of elephants worldwide.", category: CATEGORIES.ENVIRONMENT, emoji: "🐘" },
  { date: "08-15", name: "India Independence Day", description: "Celebrates India's independence from British rule on 15 August 1947 — national holiday.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },
  { date: "08-19", name: "World Photography Day", description: "Celebrates photography as an art, science and storytelling medium.", category: CATEGORIES.CULTURAL, emoji: "📸" },
  { date: "08-26", name: "Eid-e-Milad (Prophet's Birthday)", description: "Celebration of Prophet Muhammad's birthday — prayers, processions and charity. Gazetted holiday in India. (Tentative.)", category: CATEGORIES.FESTIVAL, emoji: "🌙" },
  { date: "08-26", name: "Onam (Thiruvonam)", description: "Kerala's harvest festival — ten-day celebrations with Pookalam, Vallam Kali boat race and Onam Sadhya feast.", category: CATEGORIES.FESTIVAL, emoji: "🌺" },
  { date: "08-27", name: "Raksha Bandhan", description: "Celebration of the bond between siblings — sisters tie a rakhi on brothers' wrists for protection. Falls on 27 August in 2026.", category: CATEGORIES.FESTIVAL, emoji: "🪢" },

  { date: "08-29", name: "National Sports Day (India)", description: "Celebrates hockey legend Major Dhyan Chand's birthday.", category: CATEGORIES.INDIA, emoji: "🏑" },

  // ── SEPTEMBER ──
  { date: "09-02", name: "World Coconut Day", description: "Promotes cultivation and wide use of coconuts worldwide.", category: CATEGORIES.WORLD, emoji: "🥥" },
  { date: "09-05", name: "Teachers' Day (India)", description: "Honors Dr. Sarvepalli Radhakrishnan's birthday and celebrates teachers across India.", category: CATEGORIES.INDIA, emoji: "👨‍🏫" },
  { date: "09-05", name: "International Day of Charity", description: "Encourages charitable activities by individuals, organizations and NGOs.", category: CATEGORIES.INTERNATIONAL, emoji: "💝" },
  { date: "09-07", name: "Brazil Independence Day", description: "Celebrates Brazil's independence from Portugal proclaimed on 7 September 1822.", category: CATEGORIES.INTERNATIONAL, emoji: "🇧🇷" },
  { date: "09-08", name: "International Literacy Day", description: "Highlights importance of literacy to individuals, communities and societies.", category: CATEGORIES.EDUCATION, emoji: "📖" },
  { date: "09-10", name: "World Suicide Prevention Day", description: "Raises awareness about suicide prevention and the importance of mental health.", category: CATEGORIES.HEALTH, emoji: "💚" },
  { date: "09-13", name: "World Sepsis Day", description: "A global initiative to raise public awareness of sepsis, a leading cause of death worldwide.", category: CATEGORIES.HEALTH, emoji: "🆘" },
  { date: "09-17", name: "World Patient Safety Day", description: "Aims to raise global awareness about patient safety and encourage solidarity and action.", category: CATEGORIES.HEALTH, emoji: "🛡️" },
  { date: "09-04", name: "Janmashtami", description: "Hindu festival celebrating the birth of Lord Krishna — midnight prayers, dahi handi and bhajans. Gazetted holiday in India.", category: CATEGORIES.FESTIVAL, emoji: "🪈" },
  { date: "09-14", name: "Ganesh Chaturthi", description: "Hindu festival celebrating the birth of Lord Ganesha — 10-day celebrations with idol immersion.", category: CATEGORIES.FESTIVAL, emoji: "🐘" },
  { date: "09-14", name: "Hindi Diwas (India)", description: "Celebrates adoption of Hindi as an official language of India in 1949.", category: CATEGORIES.INDIA, emoji: "🗣️" },
  { date: "09-15", name: "International Day of Democracy", description: "Celebrates democratic values and promotes development of democracy worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "🗳️" },
  { date: "09-15", name: "Engineers' Day (India)", description: "Celebrates birthday of Sir M. Visvesvaraya, eminent Indian engineer.", category: CATEGORIES.INDIA, emoji: "⚙️" },
  { date: "09-16", name: "World Ozone Day", description: "Marks the signing of the Montreal Protocol on ozone-depleting substances.", category: CATEGORIES.ENVIRONMENT, emoji: "🌐" },
  { date: "09-21", name: "International Day of Peace", description: "A day of global ceasefire and non-violence, as an ideal for all humanity.", category: CATEGORIES.INTERNATIONAL, emoji: "🕊️" },
  { date: "09-21", name: "World Alzheimer's Day", description: "Raises awareness and challenges the stigma surrounding Alzheimer's disease and dementia.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "09-25", name: "World Lung Day", description: "A day for lung health advocacy and action, an opportunity for us all to unite and promote better lung health globally.", category: CATEGORIES.HEALTH, emoji: "🫁" },
  { date: "09-28", name: "World Rabies Day", description: "Raises awareness about rabies prevention and to highlight progress in defeating this horrifying disease.", category: CATEGORIES.HEALTH, emoji: "🐕‍🦺" },
  { date: "09-29", name: "World Heart Day", description: "Informs people about the risk of cardiovascular disease and how to prevent it.", category: CATEGORIES.HEALTH, emoji: "❤️" },

  // ── OCTOBER ──
  { date: "10-01", name: "International Day of Older Persons", description: "Raises awareness of opportunities and challenges for ageing populations worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "👴" },
  { date: "10-02", name: "Gandhi Jayanti (India)", description: "Birthday of Mahatma Gandhi — also observed as International Day of Non-Violence.", category: CATEGORIES.INDIA, emoji: "🙏" },
  { date: "10-04", name: "World Animal Day", description: "Celebrates animal rights and welfare around the world.", category: CATEGORIES.ENVIRONMENT, emoji: "🐾" },
  { date: "10-05", name: "World Teachers' Day", description: "Celebrates the teaching profession worldwide and teachers' contributions.", category: CATEGORIES.EDUCATION, emoji: "👩‍🏫" },
  { date: "10-08", name: "Indian Air Force Day", description: "Celebrates establishment of the Indian Air Force in 1932.", category: CATEGORIES.INDIA, emoji: "✈️" },
  { date: "10-10", name: "World Mental Health Day", description: "Raises awareness of mental health issues and advocates for better mental health care.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "10-12", name: "World Arthritis Day", description: "Focuses on raising awareness of the issues affecting people with rheumatic and musculoskeletal diseases.", category: CATEGORIES.HEALTH, emoji: "🦴" },
  { date: "10-13", name: "World Thrombosis Day", description: "Focuses attention on the often overlooked cause of the number one killer: cardiovascular disease.", category: CATEGORIES.HEALTH, emoji: "🩸" },
  { date: "10-15", name: "Global Handwashing Day", description: "An international advocacy day dedicated to increasing awareness and understanding about the importance of handwashing.", category: CATEGORIES.HEALTH, emoji: "🧼" },
  { date: "10-16", name: "World Spine Day", description: "Raises awareness about spinal health and the importance of physical activity and posture in preventing spinal conditions.", category: CATEGORIES.HEALTH, emoji: "🧘" },
  { date: "10-16", name: "World Anaesthesia Day", description: "Commemorates the first successful demonstration of diethyl ether anaesthesia in 1846.", category: CATEGORIES.HEALTH, emoji: "😴" },
  { date: "10-17", name: "World Trauma Day", description: "Emphasizes the importance of saving and protecting a life during the most critical moments and the prevention of trauma.", category: CATEGORIES.HEALTH, emoji: "⛑️" },
  { date: "10-20", name: "World Osteoporosis Day", description: "Dedicated to raising global awareness of the prevention, diagnosis and treatment of osteoporosis.", category: CATEGORIES.HEALTH, emoji: "🦴" },
  { date: "10-24", name: "World Polio Day", description: "Provides an opportunity to highlight global efforts toward a polio-free world.", category: CATEGORIES.HEALTH, emoji: "💊" },
  { date: "10-29", name: "World Stroke Day", description: "Provides a global platform for the stroke community to drive action on stroke prevention and advocacy.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "10-11", name: "Shardiya Navratri Begins", description: "Nine nights of worship of Goddess Durga — Garba, Dandiya and fasting across India.", category: CATEGORIES.FESTIVAL, emoji: "🪔" },
  { date: "10-16", name: "World Food Day", description: "Promotes awareness of hunger and the need for global food security.", category: CATEGORIES.WORLD, emoji: "🍽️" },
  { date: "10-20", name: "Dussehra (Vijayadashami)", description: "Hindu festival celebrating the victory of Lord Rama over Ravana — Ramlila and effigy burning.", category: CATEGORIES.FESTIVAL, emoji: "🏹" },
  { date: "10-24", name: "United Nations Day", description: "Celebrates entry into force of the United Nations Charter in 1945.", category: CATEGORIES.INTERNATIONAL, emoji: "🌐" },
  { date: "10-31", name: "Halloween", description: "Western holiday with costumes, trick-or-treating, jack-o'-lanterns and spooky fun.", category: CATEGORIES.CULTURAL, emoji: "🎃" },
  { date: "10-31", name: "National Unity Day (India – Rashtriya Ekta Diwas)", description: "Birth anniversary of Sardar Vallabhbhai Patel, Iron Man of India.", category: CATEGORIES.INDIA, emoji: "🇮🇳" },

  // ── NOVEMBER ──
  { date: "11-01", name: "World Vegan Day", description: "Celebrates veganism and promotes plant-based lifestyle for health and environment.", category: CATEGORIES.WORLD, emoji: "🌱" },
  { date: "11-06", name: "Dhanteras", description: "First day of Diwali festivities — buying gold, silver and new items brings prosperity and good luck.", category: CATEGORIES.FESTIVAL, emoji: "🏺" },
  { date: "11-07", name: "Chhoti Diwali (Narak Chaturdashi)", description: "Day before main Diwali — diyas lit at dawn, sweets shared, firecrackers celebrated.", category: CATEGORIES.FESTIVAL, emoji: "🪔" },
  { date: "11-05", name: "World Tsunami Awareness Day", description: "Promotes tsunami risk reduction through education and international cooperation.", category: CATEGORIES.WORLD, emoji: "🌊" },
  { date: "11-08", name: "Diwali – Festival of Lights", description: "The grandest Hindu festival — homes lit with diyas, fireworks, sweets exchanged and Lakshmi puja.", category: CATEGORIES.FESTIVAL, emoji: "🪔" },
  { date: "11-11", name: "Bhai Dooj", description: "Festival celebrating the bond between brothers and sisters — celebrated on the 5th day of Diwali.", category: CATEGORIES.FESTIVAL, emoji: "👫" },
  { date: "11-10", name: "World Science Day for Peace", description: "Highlights the important role of science in society and promoting peace.", category: CATEGORIES.SCIENCE, emoji: "🔬" },
  { date: "11-12", name: "National Education Day (India)", description: "Celebrates birthday of Maulana Abul Kalam Azad, India's first Education Minister.", category: CATEGORIES.INDIA, emoji: "📚" },
  { date: "11-13", name: "World Kindness Day", description: "Promotes kindness as a universal value transcending borders and beliefs.", category: CATEGORIES.CULTURAL, emoji: "💛" },
  { date: "11-14", name: "Children's Day (India)", description: "Celebrates Jawaharlal Nehru's birthday — festivities for children across schools.", category: CATEGORIES.INDIA, emoji: "🎈" },
  { date: "11-07", name: "National Cancer Awareness Day (India)", description: "Raises awareness about cancer prevention, early detection, and treatment in India.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "11-08", name: "World Radiography Day", description: "Commemorates the anniversary of the discovery of X-rays and promotes radiography as a career.", category: CATEGORIES.HEALTH, emoji: "🩻" },
  { date: "11-12", name: "World Pneumonia Day", description: "Raises awareness about pneumonia, the world's leading infectious killer of children under five.", category: CATEGORIES.HEALTH, emoji: "🫁" },
  { date: "11-14", name: "World Diabetes Day", description: "Raises awareness about diabetes as a critical global health issue.", category: CATEGORIES.HEALTH, emoji: "🩺" },
  { date: "11-17", name: "National Epilepsy Day (India)", description: "Focuses on raising awareness about epilepsy in India and reducing stigma.", category: CATEGORIES.HEALTH, emoji: "🧠" },
  { date: "11-18", name: "World Antimicrobial Awareness Week Begins", description: "Aims to increase awareness of global antimicrobial resistance and to encourage best practices.", category: CATEGORIES.HEALTH, emoji: "💊" },
  { date: "11-19", name: "World Pancreatic Cancer Day", description: "A global campaign to raise awareness about pancreatic cancer and recognize its symptoms.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "11-24", name: "Guru Nanak Jayanti (Gurpurab)", description: "Celebrates the birth of Guru Nanak Dev Ji, founder of Sikhism — langar, kirtan and nagar kirtan. Gazetted holiday in India.", category: CATEGORIES.FESTIVAL, emoji: "🛕" },
  { date: "11-16", name: "International Day for Tolerance", description: "Fosters mutual understanding among cultures and peoples worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "🤝" },
  { date: "11-19", name: "World Toilet Day", description: "Raises awareness about the global sanitation crisis affecting billions.", category: CATEGORIES.WORLD, emoji: "🚽" },
  { date: "11-20", name: "Universal Children's Day", description: "Promotes international togetherness and awareness among children worldwide.", category: CATEGORIES.INTERNATIONAL, emoji: "👦" },
  { date: "11-25", name: "International Day for Elimination of Violence Against Women", description: "Raises awareness of violence against women and promotes action globally.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "🟠" },
  { date: "11-26", name: "Constitution Day (India – Samvidhan Diwas)", description: "Celebrates adoption of India's landmark Constitution on 26 November 1949.", category: CATEGORIES.INDIA, emoji: "📜" },
  { date: "11-28", name: "Thanksgiving Day (USA)", description: "American holiday celebrating harvest and blessings — family gatherings and the iconic Thanksgiving feast. (Fourth Thursday of November.)", category: CATEGORIES.CULTURAL, emoji: "🦃" },
  { date: "11-30", name: "Computer Security Day", description: "Promotes awareness of computer and cybersecurity issues to protect data.", category: CATEGORIES.SCIENCE, emoji: "🔐" },

  // ── DECEMBER ──
  { date: "12-01", name: "World AIDS Day", description: "International day dedicated to raising awareness of the AIDS pandemic.", category: CATEGORIES.HEALTH, emoji: "🎗️" },
  { date: "12-02", name: "National Pollution Control Day (India)", description: "Promotes prevention and control of industrial pollution in India.", category: CATEGORIES.INDIA, emoji: "🌿" },
  { date: "12-03", name: "World Day of Persons with Disabilities", description: "Promotes rights and wellbeing of persons with disabilities worldwide.", category: CATEGORIES.WORLD, emoji: "♿" },
  { date: "12-04", name: "Indian Navy Day", description: "Celebrates the Indian Navy's decisive role in the 1971 war with Pakistan.", category: CATEGORIES.INDIA, emoji: "⚓" },
  { date: "12-05", name: "World Soil Day", description: "Focuses on the importance of healthy soil and its sustainable management.", category: CATEGORIES.ENVIRONMENT, emoji: "🌱" },
  { date: "12-09", name: "International Anti-Corruption Day", description: "Raises awareness about corruption and promotes anti-corruption measures globally.", category: CATEGORIES.INTERNATIONAL, emoji: "🚫" },
  { date: "12-10", name: "Human Rights Day", description: "Marks the anniversary of the Universal Declaration of Human Rights in 1948.", category: CATEGORIES.HUMAN_RIGHTS, emoji: "✊" },
  { date: "12-11", name: "International Mountain Day", description: "Raises awareness of the importance of mountains to life and sustainability.", category: CATEGORIES.ENVIRONMENT, emoji: "⛰️" },
  { date: "12-12", name: "Universal Health Coverage Day", description: "Calls for quality health services for all people, everywhere without financial hardship.", category: CATEGORIES.HEALTH, emoji: "🏥" },
  { date: "12-14", name: "National Energy Conservation Day (India)", description: "Promotes awareness about energy conservation and efficiency in India.", category: CATEGORIES.INDIA, emoji: "⚡" },
  { date: "12-16", name: "Vijay Diwas (India)", description: "India's Victory Day — celebrates victory over Pakistan in the 1971 war.", category: CATEGORIES.INDIA, emoji: "🎖️" },
  { date: "12-22", name: "National Mathematics Day (India)", description: "Celebrates birthday of Srinivasa Ramanujan, legendary mathematician.", category: CATEGORIES.INDIA, emoji: "🔢" },
  { date: "12-23", name: "Kisan Diwas – National Farmers' Day (India)", description: "Celebrates birthday of former PM Chaudhary Charan Singh — champion of Indian farmers.", category: CATEGORIES.INDIA, emoji: "🌾" },
  { date: "12-24", name: "Christmas Eve", description: "Evening before Christmas — church services, carol singing and family gatherings.", category: CATEGORIES.FESTIVAL, emoji: "🎄" },
  { date: "12-25", name: "Christmas Day", description: "Christian festival celebrating the birth of Jesus Christ — gifts, feasts and carols worldwide.", category: CATEGORIES.FESTIVAL, emoji: "🎄" },
  { date: "12-25", name: "Good Governance Day (India)", description: "Celebrates birthday of former PM Atal Bihari Vajpayee — promoting good governance.", category: CATEGORIES.INDIA, emoji: "🏛️" },
  { date: "12-31", name: "New Year's Eve", description: "Last day of the year — celebrated worldwide with parties, fireworks and celebrations.", category: CATEGORIES.CULTURAL, emoji: "🎆" },
];
